pipeline {
    agent any

    environment {
        APP_NAME = "react-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/pheaktra01/test-deploy.git'
            }
        }

        stage('Move to app directory') {
            steps {
                dir('app') {
                    sh 'ls -la'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                sh '''
                docker run --rm \
                -v "/var/lib/jenkins/workspace/Test Deployment/app:/app" \
                -w /app \
                node:20-alpine \
                sh -c "npm install && npm run build"
                '''
            }
        }

        stage('Test') {
            steps {
                dir('app') {
                    sh 'npm test -- --watchAll=false || true'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('app') {
                    sh 'npx eslint . || true'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    sh "docker build -t ${APP_NAME}:latest ."
                }
            }
        }

        stage('Deploy with Ansible') {
            steps {
                dir('app') {
                    sh "ansible-playbook -i inventory.ini deploy.yml"
                }
            }
        }
    }

    post {
        success {
            echo "🚀 Build, Test, Docker Build, Deploy SUCCESS!"
        }

        failure {
            echo "❌ Pipeline FAILED"
        }
    }
}