pipeline {
    agent any

    environment {
        APP_NAME = "react-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/pheaktra01/test-deploy.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test -- --watchAll=false'
            }
        }

        stage('Lint (Optional)') {
            steps {
                sh 'npx eslint . || true'
            }
        }

        stage('Docker Build') {
            steps {
                sh "docker build -t ${APP_NAME}:latest ."
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh """
                ansible-playbook -i inventory.ini deploy-react.yml
                """
            }
        }
    }

    post {
        success {
            echo "🚀 Build, Test, and Deploy SUCCESS!"
        }

        failure {
            echo "❌ Pipeline FAILED"
        }
    }
}